trigger:
  branches:
    include:
    - refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    fetchDepth: 1
  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false
  - task: ArchiveFiles@2
    displayName: 'Archive '
    inputs:
      rootFolderOrFile: D:\a\1\s
      includeRootFolder: false
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
    inputs:
      path: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifactName: drop
  - task: CopyPublishBuildArtifacts@1
    displayName: 'Copy Publish Artifact: drop'
    enabled: False
    inputs:
      Contents: '**'
      ArtifactName: drop
      ArtifactType: Container
